export default class Constants {
    static BUTTON_DELETE = 'delete'
    static BUTTON_EDIT = 'edit'
    static BUTTON_REDO = 'redo'
    static BUTTON_VARY = 'vary'
    static BUTTON_VARIANT = 'variant'
    static BUTTON_UPRES = 'upres'
    static BUTTON_UPRESSING = 'upressing'
    static COMMAND_GEN = 'gen'
    static OPTION_PROMPT = 'prompt'
    static OPTION_NEGATIVE_PROMPT = 'negative-prompt'
    static OPTION_COUNT = 'count'
    static OPTION_ASPECT_RATIO = 'aspect-ratio'
    static PROMPT_EDIT = 'prompt-edit'
    static PROMPT_REDO = 'prompt-redo'
    static INPUT_NEW_PROMPT = 'new-prompt'
    static INPUT_NEW_NEGATIVE_PROMPT = 'new-negative-prompt'
}