export default class Constants {
    static BUTTON_DELETE = 'delete'
    static BUTTON_EDIT = 'edit'
    static BUTTON_REDO = 'redo'
    static BUTTON_VARY = 'vary'
    static BUTTON_VARY_CHOICE = 'vary-choice'
    static BUTTON_UPSCALE = 'upscale'
    static BUTTON_UPSCALE_CHOICE = 'upscale-choice'
    static BUTTON_DETAIL = 'detail'
    static BUTTON_DETAIL_CHOICE = 'detail-choice'
    static BUTTON_INFO = 'info'
    static BUTTON_INFO_CHOICE = 'info-choice'
    static BUTTON_DEAD = 'dead'

    static COMMAND_GEN = 'gen'
    static COMMAND_SET = 'set'
    static OPTION_PROMPT = 'prompt'
    static OPTION_NEGATIVE_PROMPT = 'negative-prompt'
    static OPTION_COUNT = 'count'
    static OPTION_ASPECT_RATIO = 'aspect-ratio'
    static OPTION_SPOILER = 'spoiler'
    static OPTION_SIZE = 'size'
    static OPTION_HIRES = 'hires'

    static COMMAND_SPAM = 'spam'
    static SUBCOMMAND_SPAM_THREAD = 'thread'
    static OPTION_SPAM_TITLE = 'title'
    static SUBCOMMAND_SPAM_ON = 'on'
    static SUBCOMMAND_SPAM_OFF = 'off'

    static COMMAND_CANCEL = 'cancel'
    static OPTION_CANCEL_SELECTION = 'selection'

    static COMMAND_HELP = 'help'
    static OPTION_HELP_SECTION = 'section'
    static OPTION_HELP_GENERAL = 'general'
    static OPTION_HELP_GEN = 'gen'
    static OPTION_HELP_BUTTONS = 'buttons'
    static OPTION_HELP_SPAM = 'spam'
    static OPTION_HELP_SETTINGS = 'settings'
    static OPTION_HELP_PARAMS = 'params'
    static OPTION_HELP_TEXT = 'text'
    static OPTION_HELP_WORKFLOW = 'workflow'

    static COMMAND_PARAM = 'param'
    static SUBCOMMAND_PARAM_SET = 'set'
    static SUBCOMMAND_PARAM_UNSET = 'unset'
    static OPTION_PARAM_NAME = 'name'
    static OPTION_PARAM_VALUE = 'value'

    static COMMAND_LIST = 'list'
    static SUBCOMMAND_LIST_PARAMS = 'params'
    static SUBCOMMAND_LIST_SETTINGS = 'settings'

    static COMMAND_TEXT = 'text'
    static OPTION_TEXT_INPUT = 'input'
    static OPTION_FONT = 'font'
    static OPTION_FONT_SIZE = 'size'
    static OPTION_FONT_ITALIC = 'italic'
    static OPTION_FONT_BOLD = 'bold'

    static PROMPT_PROMPT = 'prompt-prompt'
    static PROMPT_EDIT = 'prompt-edit'
    static PROMPT_REDO = 'prompt-redo'
    static INPUT_NEW_SIZE = 'new-size'
    static INPUT_NEW_COUNT = 'new-count'
    static INPUT_NEW_PROMPT = 'new-prompt'
    static INPUT_NEW_NEGATIVE_PROMPT = 'new-negative-prompt'
    static INPUT_NEW_HIRES = 'new-hires'

    static BUTTON_SPAM_THREAD_CANCEL = 'spam-thread-cancel'
    static BUTTON_SPAM_THREAD_OK = 'spam-thread-ok'
    static PROMPT_THREAD = 'prompt-thread'
    static INPUT_THREAD_TITLE = 'thread-title'
}