export default class Constants {
    static BUTTON_DELETE = 'delete'
    static BUTTON_EDIT = 'edit'
    static BUTTON_REDO = 'redo'
    static BUTTON_VARY = 'vary'
    static BUTTON_VARY_CHOICE = 'vary-choice'
    static BUTTON_UPSCALE = 'upscale'
    static BUTTON_UPSCALE_CHOICE = 'upscale-choice'
    static BUTTON_DETAIL = 'detail'
    static BUTTON_DETAIL_CHOICE = 'detail-choice'
    static BUTTON_INFO = 'info'
    static BUTTON_INFO_CHOICE = 'info-choice'
    static BUTTON_DEAD = 'dead'

    static COMMAND_GEN = 'gen'
    static OPTION_PROMPT = 'prompt'
    static OPTION_NEGATIVE_PROMPT = 'negative-prompt'
    static OPTION_COUNT = 'count'
    static OPTION_ASPECT_RATIO = 'aspect-ratio'
    static OPTION_SPOILER = 'spoiler'

    static PROMPT_EDIT = 'prompt-edit'
    static PROMPT_REDO = 'prompt-redo'
    static INPUT_NEW_PROMPT = 'new-prompt'
    static INPUT_NEW_NEGATIVE_PROMPT = 'new-negative-prompt'
    static FIELD_USER = 'User'
    static FIELD_PROMPT = 'Prompt'
    static FIELD_NEGATIVE_PROMPT = 'Negative-Prompt'
    static FIELD_COUNT = 'Count'
    static FIELD_ASPECT_RATIO = 'Aspect-Ratio'
    static FIELD_SPOILER = 'Spoiler'
}